# Generated by Django 5.1 on 2024-10-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='merch',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cant', models.IntegerField()),
            ],
        ),
    ]
